package com.studytrack.app.auth

import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.EditText
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.core.view.isVisible
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.findNavController
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import com.studytrack.app.R
import com.studytrack.app.databinding.FragmentLoginBinding
import com.studytrack.app.util.ApiResult
import com.studytrack.app.util.InputValidators
import com.studytrack.app.util.hideKeyboard
import com.studytrack.app.util.toast
import kotlinx.coroutines.launch

/**
 * Sign-in screen: email/password, password reset, and Google sign-in.
 *
 * Google uses the ID-token flow — the SDK returns a token which Firebase
 * exchanges for a session. That requires the Google provider to be enabled in
 * the Firebase console and this build's SHA-1 fingerprint to be registered;
 * without them the SDK fails with DEVELOPER_ERROR (code 10), which is surfaced
 * as an actionable message rather than a silent no-op.
 */
class LoginFragment : Fragment() {

    private var _binding: FragmentLoginBinding? = null
    private val binding get() = _binding!!

    private val viewModel: AuthViewModel by viewModels { AuthViewModel.FACTORY }

    private lateinit var googleSignInLauncher: ActivityResultLauncher<Intent>

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentLoginBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        googleSignInLauncher = registerForActivityResult(
            ActivityResultContracts.StartActivityForResult()
        ) { result -> handleGoogleResult(result.data) }

        binding.loginButton.setOnClickListener {
            hideKeyboard()
            if (validate()) {
                viewModel.login(
                    email = binding.emailField.text.toString().trim(),
                    password = binding.passwordField.text.toString()
                )
            }
        }

        binding.forgotPasswordLink.setOnClickListener { promptPasswordReset() }

        binding.googleButton.setOnClickListener { startGoogleSignIn() }

        binding.microsoftButton.setOnClickListener {
            toast(getString(R.string.auth_microsoft_unavailable))
        }

        binding.registerLink.setOnClickListener {
            findNavController().navigate(LoginFragmentDirections.actionLoginFragmentToRegisterFragment())
        }

        viewLifecycleOwner.lifecycleScope.launch {
            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
                viewModel.loginState.collect { state -> renderState(state) }
            }
        }
    }

    // ------------------------------------------------------------- Google flow

    private fun startGoogleSignIn() {
        // default_web_client_id is generated by the google-services plugin from
        // the Web OAuth client in google-services.json.
        val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id))
            .requestEmail()
            .build()
        val client = GoogleSignIn.getClient(requireContext(), options)
        googleSignInLauncher.launch(client.signInIntent)
    }

    private fun handleGoogleResult(data: Intent?) {
        try {
            val account = GoogleSignIn.getSignedInAccountFromIntent(data)
                .getResult(ApiException::class.java)
            val idToken = account.idToken
            if (idToken.isNullOrBlank()) {
                showError(getString(R.string.auth_google_no_token))
            } else {
                viewModel.signInWithGoogle(idToken)
            }
        } catch (e: ApiException) {
            // Code 10 = DEVELOPER_ERROR: provider disabled or SHA-1 not
            // registered. Code 12501 = the user closed the picker.
            showError(
                if (e.statusCode == GOOGLE_USER_CANCELLED) {
                    getString(R.string.auth_google_cancelled)
                } else {
                    getString(R.string.auth_google_unavailable)
                }
            )
        }
    }

    // -------------------------------------------------------- password reset

    private fun promptPasswordReset() {
        val input = EditText(requireContext()).apply {
            hint = getString(R.string.hint_email_example)
            setText(binding.emailField.text.toString().trim())
            val pad = (16 * resources.displayMetrics.density).toInt()
            setPadding(pad, pad / 2, pad, pad / 2)
        }
        MaterialAlertDialogBuilder(requireContext())
            .setTitle(R.string.action_forgot_password)
            .setMessage(R.string.password_reset_prompt)
            .setView(input)
            .setNegativeButton(R.string.action_cancel, null)
            .setPositiveButton(R.string.action_send_link) { _, _ ->
                val email = input.text.toString().trim()
                if (!InputValidators.isValidEmail(email)) {
                    binding.emailLayout.error = getString(R.string.error_email_invalid)
                } else {
                    binding.emailLayout.error = null
                    viewModel.sendPasswordReset(email) { message -> toast(message) }
                }
            }
            .show()
    }

    // ----------------------------------------------------------------- render

    private fun validate(): Boolean {
        var valid = true

        if (!InputValidators.isValidEmail(binding.emailField.text.toString().trim())) {
            binding.emailLayout.error = getString(R.string.error_email_invalid)
            valid = false
        } else {
            binding.emailLayout.error = null
        }

        if (binding.passwordField.text.toString().isEmpty()) {
            binding.passwordLayout.error = getString(R.string.error_password_required)
            valid = false
        } else {
            binding.passwordLayout.error = null
        }

        return valid
    }

    private fun renderState(state: ApiResult<Unit>?) {
        val loading = state is ApiResult.Loading
        binding.loginProgress.isVisible = loading
        binding.loginButton.isEnabled = !loading
        binding.emailLayout.isEnabled = !loading
        binding.passwordLayout.isEnabled = !loading
        binding.googleButton.isEnabled = !loading

        if (state is ApiResult.Error) {
            showError(state.message)
        } else {
            binding.errorText.isVisible = false
        }
        // On Success: no navigation here — MainActivity's FirebaseAuth
        // AuthStateListener routes to the dashboard (single navigation path).
    }

    private fun showError(message: String) {
        binding.errorText.text = message
        binding.errorText.isVisible = true
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    private companion object {
        /** GoogleSignInStatusCodes.SIGN_IN_CANCELLED (the user backed out). */
        const val GOOGLE_USER_CANCELLED = 12501
    }
}
